services:
    Bafford\ElasticaExtraBundle\Provider\ElasticSearchProvider:
        class: Bafford\ElasticaExtraBundle\Provider\ElasticSearchProvider
        arguments:
            $config: '%bafford_elastica_extra.config%'
        calls:
            - [ setContainer, ["@service_container"] ]

